command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
env:
  - name: AGENT_MODE
    value: "real"
  - name: GIS_CLUSTER_ID
    value: "1031-100220-elaoqpmd"
  - name: GENIE_SPACE_ID
    value: "01f164dda12514ad8940be29a049870c"
  - name: GENIE_SPACE_FACILITIES
    value: "01f16b0f00271be69d67170685241974"
  - name: DATABRICKS_HOST
    value: "https://adb-6884316730967297.17.azuredatabricks.net"
  - name: DATABRICKS_TOKEN
    valueFrom: user_pat
  - name: GIS_USER_PAT
    valueFrom: user_pat
  - name: LLM_ENDPOINT
    value: "mas-33c3b825-endpoint"
  - name: TBL_ZIP5
    value: "edlprod.geo_analytics.usps_zip5"
  - name: TBL_FACILITIES
    value: "edlprod.geo_analytics.facilities_fc"
  - name: TBL_BOXES
    value: "edlprod.geo_analytics.cpms_co_t"
